
version: '3.8'

services:
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: xdata-backend
    ports:
      - "8001:8000"
    env_file:
      - ./app/backend/.env
    volumes:
      - ./data:/app/data
      - ./charts:/app/static/charts
    restart: always

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: xdata-frontend
    ports:
      - "3000:3000"
    environment:
      # IMPORTANT: Replace localhost with your VPS Public IP. Note port 8001.
      - NEXT_PUBLIC_API_URL=http://YOUR_SERVER_IP:8001/api
    restart: always
