
version: '3.8'

services:
  backend:
    build: 
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: xdata-backend
    ports:
      - "8002:8000"
    env_file:
      - ./app/backend/.env
    volumes:
      - ./data:/app/data
      - ./charts:/app/static/charts
    restart: always

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://139.224.61.205:8002/api
    container_name: xdata-frontend
    ports:
      - "3002:3000"
    environment:
      # Production Public IP Configuration (New Port 8002)
      - NEXT_PUBLIC_API_URL=http://139.224.61.205:8002/api
    restart: always
